[package]
name = "iced_example"
version = "0.1.0"
edition = "2021"

[dependencies]
    iced = "0.10"
    tokio = {version = "1.40.0", features = ["full"] }
    log = "0.4"
    chrono = "0.4"
    image="0.24"
