[package]
name = "iced_example"
version = "0.1.0"
edition = "2021"

[dependencies]
    iced = {version = "0.10", features = ["default"]}
    tokio = {version = "1.40.0", features = ["full"] }
    log = "0.4"
    chrono = "0.4"
    fern = "0.7.0"
    image="0.24"
cpal="0.16.0"
rfd="0.15.4"